FROM ubuntu:18.04

COPY requirements_api.txt ./requirements.txt

RUN apt-get update
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7 python3-pip
RUN apt install -y libsm6 libxrender1
RUN apt install -y python-qt4 cmake curl

RUN pip3 install -r requirements.txt

WORKDIR /app
COPY . ./
#RUN mkdir -p /workdir
#WORKDIR /workdir/ml_investment_api


ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8


#CMD ["/bin/bash", "entry.sh"]
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8001"]

